name: Data Passing Example

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      message: ${{ steps.set-message.outputs.message }}
    steps:
      - id: set-message
        run: echo "message=Hello from job1" >> $GITHUB_OUTPUT

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ needs.job1.outputs.message }}"
