name: Variable Example

on: [push]

env:
  GREETING: Hello from GitHub Actions

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Use environment variable
        run: echo "$GREETING, world!"
      
      - name: Use environment variable with GitHub context
        run: echo "${{ env.GREETING }}, ${{ github.actor }}!"

